### ISSUE TITLE
Describe an alma electronic title

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#1001]
related https://github.com/pulibrary/marc_liberation/issues/921

**Comment by mzelesky** [comment]
MMS ID: 99122412208706421 (Science)

URL for current Blacklight: https://catalog.princeton.edu/catalog/9774575

Sample enrichment from general publishing:
```
951    $v 2020-12-14 07:45:22 US/Eastern $g JSTOR $u System $j updated parse param to prevent JSTOR links leading to current pub. sites; undo if EL comes up with a global fix --nb, 6/14 / JSTOR journal archives purchased as sep. packages; this combines titles from all; some titles not yet part of packages deactivated $t 2020-12-14 07:45:15 US/Eastern $x https://na07.alma.exlibrisgroup.com/view/uresolver/01PRI_INST/openurl?u.ignore_date_coverage=true&portfolio_pid=53466633730006421&Force_direct=true $s SFX $0 53466633730006421 $k  Available from 1880 volume: 1 issue: 1. Most recent 6 year(s) not available. $f true $m 61428530720006421 $n JSTOR Complete $b param $1 62428546800006421 $c d?u.ignore_date_coverage=true&rft.mms_id=99122412208706421 $a Available $l 61111034808820000 $e JOURNAL $8 53466633730006421 
953    $a 53466633730006421 $b 1880 $d 1 $f 1 $h 1 $j 1 
954    $a 53466633730006421 $b >= $c 6 
```
Sample enrichment from API bib call:
```
AVE    $8 53466633730006421 $c 61428530720006421 $e Available $m JSTOR Complete $s  Available from 1880 volume: 1 issue: 1. Most recent 6 year(s) not available. $t JSTOR $u publishing_base_url undefined?u.ignore_date_coverage=true&rft.mms_id=99122412208706421 
```
The 953 and 954 fields provide a more structured view of the same information in the 951 $k. However, the 951 is connected to the corresponding 953 and 954 fields by $8.

The information currently provided to users in production Blacklight is contained in the following subfields:
Range of years (1880-2015): corresponds to 953 $b and $c, combined with 954 information (6 year embargo marked by 954 $b and $c); not returned with the API bib call
Summary availability (Available from 1880 volume: 1 issue: 1. Most recent 6 year(s) not available.): corresponds to 951 $k and AVE $s
Database name (JSTOR Complete): corresponds to 951 $n and AVE $m
Direct link: provided in 951 $x; not returned with the API bib call
Service page link (similar to https://getit.princeton.edu/link_router/index/50274204): provided in 951 $c and AVE $u [service page is not yet configured in Alma, which is why it's not correct]

**Comment by christinach** [comment]
examples: 
https://catalog-alma-qa.princeton.edu/catalog/99122306151806421
https://catalog-alma-qa.princeton.edu/catalog/9918573506421

**Comment by christinach** [comment]
This is done.
