### ISSUE TITLE
STFP is not working

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/marc_liberation#1074]
I have no idea why or how.   There are comments in #909 .  More information should be added here

May be related to https://github.com/pulibrary/marc_liberation/issues/839

**Comment by carolyncole** [comment]
The plan is to make a small change when the timestamp is gathered.
Then on bibdata-staging2
  *  add a dump record for October 31st
  * Run rake task
  * Look in sftp RECAP_UPDATE_DIR to make sure files were generated

This should be a small subset since the last update in VGER test on November 6th.

**Comment by christinach** [comment]
History of this issue. 
1. We had a bug related to the timestamp in the rake task. This was fixed. 
2. The voyager helpers code which was uploading the files was timing out because of the excessive queries. This was fixed. 
3. After we fixed the above (@mzelesky and I), we realized that the rake task was uploading invalid marc recorcds to scsb, that scsb could not process. This is also fixed now (according to @mzelesky )
4. We only need to resume the rake task.

**Comment by carolyncole** [comment]
@christinach according to @mzelesky marc_liberation is at the latest version of voyager helpers, so 1, 2, & 3 are complete.

I'll give 4 a try...

**Comment by christinach** [comment]
From discussion with @mzelesky there are some uncomitted changes that need first to be merged in voyager helpers. then we can cut a new release update mar_liberation and resume the rake task

**Comment by christinach** [comment]
closing in favor of https://github.com/pulibrary/marc_liberation/issues/1078
