### ISSUE TITLE
Patron record encoding problems

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#136]
Voyager doesn't seem to properly encode diacritics in patron names. In our for the patron route to work it seems we need to force the name strings ascii as we've had to do for the enumeration and chron fields in item records.

**Comment by kevinreiss** [comment]
Addressed by https://github.com/pulibrary/voyager_helpers/pull/12. Will that work @tampakis.

**Comment by kevinreiss** [comment]
This is somewhat lame because if the lastname is rendering in item requests or in the account UI the user's name is truncated. However I think we are constrained by the encoding in Voyager records. This data comes from peoplesoft so perhaps there can be a fix on the patron data import that can be deployed  so we don't load bad data into the system.

**Comment by mzelesky** [comment]
In testing the method used for item data, I discovered that they are 2 separate issues. The item enumerations had the data entered as correctly as possible (i.e., a letter was followed by a non-combining diacritic). In this case, the combined character is used. Stripping the offending character will strip out the letter in addition to the diacritic. See https://bibdata.princeton.edu/patron/volkers

Instead of his last name being converted to 'Schroder', it was converted to 'Schrder.' The best way to deal with this is probably to modify the patron records themselves to remove the diacritics. Or, @tampakis, is there a problem with using I18n.transliterate to handle this?

**Comment by kevinreiss** [comment]
@mzelesky This has been corrected right?

**Comment by mzelesky** [comment]
I corrected it in voyager_helpers. But it doesn't seem like the update has taken effect on bibdata. The methods work though...

**Comment by tampakis** [comment]
Just deployed the updated voyager_helpers code. Closed by 0ee3d0f.
