### ISSUE TITLE
elf1 mfhd shows as On Order

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#159]
For Science

https://bibdata.princeton.edu/availability?id=857469

There is an elf1 heading that comes back as "On Order" dated from 2000 - https://bibdata.princeton.edu/holdings/8684831.

This seems incorrect.

**Comment by mzelesky** [comment]
MFHD 8684831 has no order information. However, Liberator is currently set to pull only the first result from VoyagerHelpers::Queries.orders(bib_id). This result is linked to MFHD ID 977093, which is a Firestone MFHD that has a status in LINE_ITEM_COPY_STATUS of 'Received Partial.' For availability, maybe the order status should be linked to each MFHD instead of just the first entry returned from the orders query for the bib.

There is a further issue in that a status of 'Received Partial' appears in the LINE_ITEM_COPY_STATUS table while the status that displays from the Purchase Order view in Acquisitions shows the status as 'Received Complete.' I have a ticket open with Ex Libris to help me understand that.
