### ISSUE TITLE
Availability Call returns empty item record

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#174]
See the last item record listed in https://bibdata.princeton.edu/availability?mfhd=538750. It consists of null values. Cataloging error? Deleted item record that didn't detach? It is odd because you don't see the same issue when you ask for the full item records, https://bibdata.princeton.edu/holdings/538750/items.

**Comment by jpstroop** [comment]
@joycebcat @mzelesky :arrow_up:

**Comment by mzelesky** [comment]
The problem seems to be that one item has no barcode. The enum/chron of the item is 1958 (Jan.-March). The item id is 5068808. I'm guessing the availability call is having trouble with that. When I tried to look at the item info in bibdata (https://bibdata.princeton.edu/items/5068808), I get a null record as well.

**Comment by kevinreiss** [comment]
If it does have an item ID (and apparently a status - this issue came up via problem reported to me by Joan and Marie with paging requests and they indicate that the "null" item has a status of missing) I think our queries for availability and full item info should probably return that data.

**Comment by kevinreiss** [comment]
From @mzelesky via email. 

```I think it’s a simple fix in the voyager_helpers code. Line 203 in liberator.rb just needs ‘unless item[:barcode].nil?’ Then it would be similar to the code that grabs the temp location.```

**Comment by tampakis** [comment]
The query to retrieve item information only works if there's a [barcode](https://github.com/pulibrary/voyager_helpers/blob/development/lib/voyager_helpers/queries.rb#L110-L111) for the item. Maybe as a fall back we can use the [brief_item_info query](https://github.com/pulibrary/voyager_helpers/blob/development/lib/voyager_helpers/queries.rb#L118-L137), which doesn't fetch the item barcode.

**Comment by mzelesky** [comment]
The other option would be to modify the query at L114 to say  (item_barcode.barcode_status = 1 OR item_barcode.barcode_status IS NULL). I did some preliminary testing of that query with the modification and it worked as I expected (2 rows were fetched, since there are two statuses associated with the item). I haven't completely thought through that yet, to think of any times when it would be a problem to return a row with a null barcode. But it's a possible way forward.
