### ISSUE TITLE
Add Voyager Location IDs to Delivery Locations

### ISSUE THREAD

**Issue by sdellis** [pulibrary/marc_liberation#194]
The [RecallPerItem API](https://developers.exlibrisgroup.com/voyager/apis/RESTfulWebServices/RecallPerItem) requires a Voyager's location ID for pickup location.  We should add these IDs to the Delivery Location data here so we can implement Recall requests through the Requests app:

https://bibdata.princeton.edu/locations/delivery_locations.json

**Comment by kevinreiss** [comment]
@sdellis somewhat counter-intuitive but looking at https://developers.exlibrisgroup.com/voyager/apis/RESTfulWebServices/RecallPerItem it seems that if you issue a GET request you'll get back some XML listing the available pickup locations and their key values. If that actually works we could use that to populate the form select element for Recallable items rather than hardcode this numeric value into the delivery location model.

**Comment by sdellis** [comment]
Ok, that might work.  I'd be a bit concerned about performance on a large serial, and I'm not sure how it's any different from any of the other delivery location data, which is all hardcoded.  At any rate, the UI is quite a challenge and I've been thinking about it... We could always remove the "disable" state of the check boxes in the Requests app for any checked out items, and just let patrons select whatever they want.  Then, we could throw up a pre-submission modal prompting the selection of Pickup Locations for anything that is Recall (or BD or ILL).  Then we could query for pickup locations and build that form for just the items they want.  Somewhat related: am I correct to assume Pickup Location options will be different for BD, ILL, and Recall?

**Comment by kevinreiss** [comment]
Think we'll solve this using the data provided by the Voyager API. Closing.
