### ISSUE TITLE
Implement Query for Current Periodical Issues

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#26]
The lack of this data is a recurring issue in staff complaints about Primo and the Library request system. See http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?holdingsinfo?&BBID=857469&pds_handle= for an example of what they'd like to see. I know this was a very expensive query but if we can find a way to deal with this in BL it would be a PR victory. 

Joyce provided me a list of all the locations that might have this sort of content http://library.princeton.edu/departments/tsd/katmandu/bookser/curriss.html for serials. I don't know that is useful in any capacity here but there are quite a few of them.

**Comment by mzelesky** [comment]
How about this? I don't think you need the receipt date or PO Number for any purposes of display (unless you think it's useful to users to know when an issue was received). We have to keep the Group By function since sometimes duplicate issues are checked in. There are very few where this is an issue (68 out of roughly 65,000), but it's enough to merit de-dupe for ease of browsing. However, I will note that the Voyager Classic OPAC does not de-dupe. 

SELECT MFHD_MASTER.MFHD_ID, SERIAL_ISSUES.ENUMCHRON
FROM ((LINE_ITEM INNER JOIN LINE_ITEM_COPY_STATUS ON LINE_ITEM.LINE_ITEM_ID = LINE_ITEM_COPY_STATUS.LINE_ITEM_ID) INNER JOIN MFHD_MASTER ON LINE_ITEM_COPY_STATUS.MFHD_ID = MFHD_MASTER.MFHD_ID) INNER JOIN (((SUBSCRIPTION INNER JOIN COMPONENT ON SUBSCRIPTION.SUBSCRIPTION_ID = COMPONENT.SUBSCRIPTION_ID) INNER JOIN ISSUES_RECEIVED ON COMPONENT.COMPONENT_ID = ISSUES_RECEIVED.COMPONENT_ID) INNER JOIN SERIAL_ISSUES ON (ISSUES_RECEIVED.ISSUE_ID = SERIAL_ISSUES.ISSUE_ID) AND (ISSUES_RECEIVED.COMPONENT_ID = SERIAL_ISSUES.COMPONENT_ID)) ON LINE_ITEM_COPY_STATUS.LINE_ITEM_ID = SUBSCRIPTION.LINE_ITEM_ID
WHERE ((SERIAL_ISSUES.RECEIVED = '1') AND (ISSUES_RECEIVED.OPAC_SUPPRESSED = '1'))
GROUP BY MFHD_MASTER.MFHD_ID, SERIAL_ISSUES.ENUMCHRON;

**Comment by mzelesky** [comment]
Ok, I realized there was an extra join to MFHD_MASTER in there. Here is a less expensive query (the first 50 rows were retrieved in half the time).
SELECT LINE_ITEM_COPY_STATUS.MFHD_ID, SERIAL_ISSUES.ENUMCHRON INTO EnumMFHDs
FROM (LINE_ITEM INNER JOIN LINE_ITEM_COPY_STATUS ON LINE_ITEM.LINE_ITEM_ID = LINE_ITEM_COPY_STATUS.LINE_ITEM_ID) INNER JOIN (((SUBSCRIPTION INNER JOIN COMPONENT ON SUBSCRIPTION.SUBSCRIPTION_ID = COMPONENT.SUBSCRIPTION_ID) INNER JOIN ISSUES_RECEIVED ON COMPONENT.COMPONENT_ID = ISSUES_RECEIVED.COMPONENT_ID) INNER JOIN SERIAL_ISSUES ON (ISSUES_RECEIVED.COMPONENT_ID = SERIAL_ISSUES.COMPONENT_ID) AND (ISSUES_RECEIVED.ISSUE_ID = SERIAL_ISSUES.ISSUE_ID)) ON LINE_ITEM_COPY_STATUS.LINE_ITEM_ID = SUBSCRIPTION.LINE_ITEM_ID
WHERE (((SERIAL_ISSUES.RECEIVED)='1') AND ((ISSUES_RECEIVED.OPAC_SUPPRESSED)='1'))
GROUP BY LINE_ITEM_COPY_STATUS.MFHD_ID, SERIAL_ISSUES.ENUMCHRON;

**Comment by mzelesky** [comment]
As for finding any common elements to which bib/mfhd combinations to run the query on, there is not much to report. There are 100 locations that have unsuppressed check-in information, and there are 281 bib records that are in formats other than serials (mostly monographs, but one integrating resource and two collections are also there). Also, I am assuming that this query will only be run on unsuppressed MFHDs. If the query has to check for that, that would bring it right back to needing to include the MFHD_MASTER table.

**Comment by mzelesky** [comment]
And from the Voyager documentation (and following the XSL document that displays current issues in the OPAC), it looks like Voyager does not use any criteria to determine whether or not to look for associated checkin data; it just looks for it for every MFHD.
