### ISSUE TITLE
Index IIIF manifest URL

### ISSUE THREAD

**Issue by escowles** [pulibrary/marc_liberation#351]

**Comment by jrgriffiniii** [comment]
I have a potential solution for this (https://github.com/pulibrary/marc_liberation/commit/a49b26febc236789c1f7e91f4091fc713edf9253), but given that Orangelight attempts to use both figgy.princeton.edu and plum.princeton.edu (https://github.com/pulibrary/orangelight/blob/master/app/assets/javascripts/plum_viewer_loader.js.coffee), anything but the path (i. e. the URL which properly resolves, the URL to the manifest, or the manifest itself) would require that indexing speed be vastly decreased due to there being at least one HTTP request passed for every record containing a valid ARK.

**Comment by jrgriffiniii** [comment]
During the wrap-up meeting held on 01/19/18, a misunderstanding on my part was corrected and it was clarified that the IIIF manifest URL could be cached within the `CacheMap` (from the Solr Documents indexed for Figgy and Plum).
