### ISSUE TITLE
On Order status isn't available in items JSON

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#47]
http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=9222024 is an "On Order" in the "Pre-Order Process" 

If has an "f" holding record, http://bibdata.princeton.edu/bibliographic/9222024/holdings but a returns the empty set for http://bibdata.princeton.edu/bibliographic/9222024/items. 

Is the query https://github.com/pulibrary/marc_liberation/blob/development/voyager_helpers/lib/voyager_helpers/queries.rb#L57 supposed to handle this? It looks like it is firing https://github.com/pulibrary/marc_liberation/blob/6663b16b8136555f989d96abcdae55083132b36c/voyager_helpers/lib/voyager_helpers/liberator.rb#L156 and should add an order key to the item response if query is successful.

**Comment by jpstroop** [comment]
It's ringing a bell with me that Janet said something about the [status values](https://github.com/pulibrary/marc_liberation/blob/development/voyager_helpers/lib/voyager_helpers/queries.rb#L59-L60) perhaps needing to be expanded in that query--right now I believe the order has to be approved.

Paging @mzelesky. Any thoughts about this? This might be another good one to rewrite.

**Comment by mzelesky** [comment]
I'll look at it today and see if there are any other values that should be included.

**Comment by jpstroop** [comment]
:+1:

**Comment by mzelesky** [comment]
Ok, I looked at it today. I should have a final query for you tomorrow morning.

**Comment by mzelesky** [comment]
Here is a revised function. If I didn't get the Ruby syntax correct, at least the query works. The 2 PO Statuses to consider are 1 (Approved/Sent) and 3 (Received Partial).


def approved_orders(bib_id)
        # PO Statuses to consider: 1, 3
        line_item_status_approved=8
        %Q(
        SELECT LINE_ITEM.BIB_ID, 
		PURCHASE_ORDER.PO_STATUS, 
		LINE_ITEM_COPY_STATUS.LINE_ITEM_STATUS, 
		LINE_ITEM_COPY_STATUS.STATUS_DATE 
		FROM ((PURCHASE_ORDER 
		INNER JOIN LINE_ITEM ON PURCHASE_ORDER.PO_ID = LINE_ITEM.PO_ID) 
		INNER JOIN LINE_ITEM_COPY_STATUS ON LINE_ITEM.LINE_ITEM_ID = LINE_ITEM_COPY_STATUS.LINE_ITEM_ID)
		WHERE (LINE_ITEM.BIB_ID = #{BIB_ID}) 
		AND ((PURCHASE_ORDER.PO_STATUS = "1" OR PURCHASE_ORDER.PO_STATUS = "3") 
		AND (LINE_ITEM_COPY_STATUS.LINE_ITEM_STATUS = #{LINE_ITEM_STATUS_APPROVED}))
        )
      end

**Comment by tampakis** [comment]
I think we need to include even more statuses. Here is a [bib](https://pulsearch.princeton.edu/catalog/9170421) that returns an unknown status in Blacklight because it doesn't have an item record yet even though a copy was received on November 24th. It has a line_item_status of 1 and a po_status of 4.
I'm thinking we should include at least po_status: 1,3,4 and line_item_status: 1,8,9

Below are all of the statuses in the po_status and line_item_status tables.
```
 PO_STATUS PO_STATUS_DESC
---------- -------------------------
	 0 Pending
	 1 Approved/Sent
	 3 Received Partial
	 4 Received Complete
	 5 Complete
	 6 Canceled

LINE_ITEM_STATUS LINE_ITEM_STATUS_DESC
---------------- -------------------------
	       0 Pending
	       1 Received Complete
	       2 Backordered
	       3 Returned
	       4 Claimed
	       5 Invoice Pending
	       6 Invoiced
	       7 Canceled
	       8 Approved
	       9 Received Partial
	      10 Rolled Over
```

**Comment by mzelesky** [comment]
The Classic OPAC says 'Received as of mm-dd-yy' for items that were received but don't yet have item records. My query above was only meant to cover items that are on order. If it is supposed to be a general query to display order information when there is no item, then yes, adding the statuses you list above is what you need. But the displayed status should not be 'On Order,' since the item is physically here.

**Comment by tampakis** [comment]
Yes exactly. I added the extra status codes so we can capture both cases with a single query, but then availability will return the appropriate status message.

-------- Original message --------
