### ISSUE TITLE
Dump all Columbia ETAS Allow/Deny into a table.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/marc_liberation#757]
The table should have five fields: `id, oclc_number, bibid, status, origin`. ID is an auto-incrementing ID. Create a unique index on oclc_number. Status should be "ALLOW" or "DENY". Origin should be "CUL". Add an index to origin and status.

https://drive.google.com/file/d/1M00nUBSvnJfaVKwpMxVzcY2Z9zfaB1Kh/view?usp=sharing 

Name the table `hathi_access`

**Comment by hackmastera** [comment]
Can we not require that the OCLC number be unique?

The data has multiple rows with the same oclc number. In the first case I see one row is "allow" and one is "deny". I'm not sure how this is possible, but it's there and I'd need to associate the status with the bibid in order to keep them straight. But then, at some point if we load more files we'll have more rows with the same oclc number. At that point we would need to make the bibid a more complex object as opposed to just being an id, since it would need to have the source as part of that object.

**Comment by mzelesky** [comment]
My guess is that in serials, there are some volumes that are public domain and some that are in copyright. Are there any items identified as monographs that have this issue?

**Comment by hackmastera** [comment]
@mzelesky The one I saw was a serial. Should we not load serials?

**Comment by mzelesky** [comment]
I don't think so, but it's just another edge case. Perhaps we can surface the URL while still blocking other access, since some issues at least are available online. I'd want us to try accessing a couple records where 'allow' and 'deny' are both on the same record.

**Comment by hackmastera** [comment]
The data was loaded in production.
