### ISSUE TITLE
Push `find_by_id` to adapters

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#786]
`find_by_id` takes an opts hash which in use is voyager-specific. The `find_by_id` method should be pushed to the adapter be invoked like
```
bib_adapter.find_by_id(id)
```

The `voyager_opts` should be moved to the voyager adapter, where the 'find_by_id' implementation would be something like
```
def find_by_id(id)
  get_bib_record(id, nil, voyager_opts)
end
```

See https://github.com/pulibrary/marc_liberation/blob/be62263a213df38810ac676c6844aca12cb70390/app/controllers/bibliographic_controller.rb#L106

**Comment by christinach** [comment]
We have scraped the fields that are coming out of the Alma publishing job in https://github.com/pulibrary/marc_liberation/issues/714
The google spreadsheet: https://github.com/pulibrary/marc_liberation/issues/749#issuecomment-673648035. To force a bib reindex we need first to decide on the fields that will need to be reindexed so that we know what API calls need to happen. These will be part of the new method in the alma adapter when passing an `mms_id` in the `find_by_id` method.
@mzelesky will have more info on these fields.

**Comment by christinach** [comment]
Created https://github.com/pulibrary/voyager_helpers/issues/118

**Comment by hackartisan** [comment]
This issue is no longer meaningful since we've removed the voyager code entirely.
