### ISSUE TITLE
SCSB exports not sending all changed records

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_liberation#839]
In the past month alone, over 1 million barcodes are attached to bib records that have been changed. The way the SCSB export is supposed to work is that any time a bib, holding, or item is updated for a ReCAP item, the bib and all associated items are exported to the SCSB server. Each day, only a few records are being exported. I'm not sure what is happening.

**Comment by christinach** [comment]
The connection to voyager fails because this block of code takes too long. https://github.com/pulibrary/voyager_helpers/blob/e3c830c68d7f2a8fdde8dcfc8339c5f1381532b3/lib/voyager_helpers/liberator.rb#L526
```
unless item_statuses.include?('In Process')
  item_barcode = get_barcode_from_item(item, c)
   barcodes << item_barcode
end
```
Tested it locally. Set a timestamp with a 24hrs difference. 
number of items it counted: 37,351 (`items = updated_recap_items(date, c)`)
  started retrieving items: 2020-10-06T20:09:21-04:00
  Finished retrieving items: 2020-10-06T20:10:07-04:00
Entered the loop: 2020-10-06T20:10:07-04:00 Looping through items
Failed with `ORA-12170: TNS:Connect timeout occurred` at : 2020-10-06T21:39:27.709679. 
When it failed it had counted: barcodes.count: 5429

Log file: https://drive.google.com/file/d/1CKIaBRyUgUXW4iNWd5Yf0S0SsdKhdJBX/view?usp=sharing

**Comment by mzelesky** [comment]
I have refactored VoyagerHelpers::Liberator.updated_recap_barcodes in a voyager_helpers branch (scsb_export). What remains is refactoring the code that dumps the records to files.
