### ISSUE TITLE
Create full dump events

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#859]
Once alma has created the files, it will fire a webhook. Use the AWS-lambda webhook listener developed as part of #645 to put an event on the AWS message queue, and subscribe to that queue from marc_liberation.

The local worker should then copy the files from the sftp server and create the dump and event objects.

amazon console is at princeton.edu/aws

**Comment by hackmastera** [comment]
Proposal:

1. Move work from https://github.com/pulibrary/alma_experimentation/pull/8/files and  https://github.com/pulibrary/alma_experimentation/pull/33/files into `marc_liberation`.
1. Update the webhook handler. If the webhook action indicates a full dump job is complete, enqueue the event body to an AWS SQS queue.
1. Use the sidekiq cron gem https://github.com/ondrejbartas/sidekiq-cron to schedule a job to run every 15 minutes as follows: ```
Check the queue and if there's an event invoke the service that will create the Dump and Event objects and copy the files.
```

This process does not need to do any indexing; full indexing is initiated manually.

**Comment by hackmastera** [comment]
SQS is free for the first million requests per month, so no issue there. https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html#sqs-pricing

**Comment by tpendragon** [comment]
Why use a cron job rather than an event listening daemon similar to Figgy's CloudFixity::Worker?

https://github.com/pulibrary/figgy/blob/40ba9ea10f26693ec887c43a4b8b1905c4b1a5bc/app/services/cloud_fixity.rb

**Comment by hackmastera** [comment]
Thanks for mentioning this. It looks like that start from a rake task -- it would die if the box was rebooted? I wanted something that would be resilient to down time.

**Comment by hackmastera** [comment]
Docs for the [QueuePoller](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/SQS/QueuePoller.html)

**Comment by tpendragon** [comment]
There's a systemd service file for it like we do for sidekiq workers, it spins back up if it dies.

**Comment by hackmastera** [comment]
https://github.com/pulibrary/princeton_ansible/blob/main/roles/pulibrary.figgy_pubsub_worker/templates/pubsub.service

Okay great this way seems better then since it can be evented in a true pub / sub way.

**Comment by hackmastera** [comment]
Here's what the webhook gives for the full publishing job:

|       @timestamp        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         @message                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|-------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2020-10-21 20:18:29.376 | 2020-10-21T20:18:29.375Z ce8e48f5-5a0b-45b2-bd3f-ee6a0524390a INFO [dd.trace_id=2849026166357774790 dd.span_id=8780004452817738765] Message received: {"id":"1429676950006421","action":"JOB_END","institution":{"value":"01PRI_INST","desc":"Princeton University"},"time":"2020-10-21T20:18:21.913Z","event":null,"job_instance":{"id":"1429676950006421","external_id":"1429676980006421","name":"Publishing Platform Job FTP Dump","submitted_by":{"value":"AlmaAdmin","desc":"Administrator, Alma"},"submit_time":"2020-10-21T19:50:43.006Z","start_time":"2020-10-21T19:50:43.022Z","end_time":"2020-10-21T20:18:21.913Z","progress":100,"status":{"value":"COMPLETED_SUCCESS","desc":"Completed Successfully"},"status_date":"2020-10-21Z","alert":[{"value":"alert_general_success","desc":"The job completed successfully. For more information view the report details."}],"counter":[{"type":{"value":"label.new.records","desc":"New Records"},"value":"109435"},{"type":{"value":"label.updated.records","desc":"Updated Records"},"value":"0"},{"type":{"value":"label.deleted.records","desc":"Deleted Records"},"value":"0"},{"type":{"value":"c.jobs.publishing.failed.publishing","desc":"Unpublished failed records"},"value":"0"},{"type":{"value":"c.jobs.publishing.skipped","desc":"Skipped records (update date changed but no data change)"},"value":"0"},{"type":{"value":"c.jobs.publishing.filtered_out","desc":"Filtered records (not published due to filter)"},"value":"0"},{"type":{"value":"c.jobs.publishing.totalRecordsWrittenToFile","desc":"Total records written to file"},"value":"0"}],"job_info":{"id":"S1425772390006421","name":"Publishing Platform Job FTP Dump","description":"Publishing Platform Job","type":{"value":"SCHEDULED","desc":"Scheduled"},"category":{"value":"PUBLISHING","desc":"Publishing"},"link":"/almaws/v1/conf/jobs/S1425772390006421"},"link":"/almaws/v1/conf/jobs/M0/instances/1429676950006421"},"bib":null,"holding":null,"item":null,"portfolio":null,"representation":null}  |

Message expanded:

```json
{
    "id": "1429676950006421",
    "action": "JOB_END",
    "institution": {
        "value": "01PRI_INST",
        "desc": "Princeton University"
    },
    "time": "2020-10-21T20:18:21.913Z",
    "event": null,
    "job_instance": {
        "id": "1429676950006421",
        "external_id": "1429676980006421",
        "name": "Publishing Platform Job FTP Dump",
        "submitted_by": {
            "value": "AlmaAdmin",
            "desc": "Administrator, Alma"
        },
        "submit_time": "2020-10-21T19:50:43.006Z",
        "start_time": "2020-10-21T19:50:43.022Z",
        "end_time": "2020-10-21T20:18:21.913Z",
        "progress": 100,
        "status": {
            "value": "COMPLETED_SUCCESS",
            "desc": "Completed Successfully"
        },
        "status_date": "2020-10-21Z",
        "alert": [
            {
                "value": "alert_general_success",
                "desc": "The job completed successfully. For more information view the report details."
            }
        ],
        "counter": [
            {
                "type": {
                    "value": "label.new.records",
                    "desc": "New Records"
                },
                "value": "109435"
            },
            {
                "type": {
                    "value": "label.updated.records",
                    "desc": "Updated Records"
                },
                "value": "0"
            },
            {
                "type": {
                    "value": "label.deleted.records",
                    "desc": "Deleted Records"
                },
                "value": "0"
            },
            {
                "type": {
                    "value": "c.jobs.publishing.failed.publishing",
                    "desc": "Unpublished failed records"
                },
                "value": "0"
            },
            {
                "type": {
                    "value": "c.jobs.publishing.skipped",
                    "desc": "Skipped records (update date changed but no data change)"
                },
                "value": "0"
            },
            {
                "type": {
                    "value": "c.jobs.publishing.filtered_out",
                    "desc": "Filtered records (not published due to filter)"
                },
                "value": "0"
            },
            {
                "type": {
                    "value": "c.jobs.publishing.totalRecordsWrittenToFile",
                    "desc": "Total records written to file"
                },
                "value": "0"
            }
        ],
        "job_info": {
            "id": "S1425772390006421",
            "name": "Publishing Platform Job FTP Dump",
            "description": "Publishing Platform Job",
            "type": {
                "value": "SCHEDULED",
                "desc": "Scheduled"
            },
            "category": {
                "value": "PUBLISHING",
                "desc": "Publishing"
            },
            "link": "/almaws/v1/conf/jobs/S1425772390006421"
        },
        "link": "/almaws/v1/conf/jobs/M0/instances/1429676950006421"
    },
    "bib": null,
    "holding": null,
    "item": null,
    "portfolio": null,
    "representation": null
}
```

**Comment by hackmastera** [comment]
The job has a "profile id" of `1395961370006421` but that doesn't appear to be included in the webhook message. The only way to identify these jobs is by the profile name ("FTP Dump") prepended by the job type ("Publishing Platform Job").

**Comment by hackmastera** [comment]
Notes:

1. figgy-deploy is the profile we built for deploying the image server for figgy (the iiif-lambda stuff). A profile is just a user with a bunch of permissions. Do we want to keep this profile or use a different one? Maybe ask @kayiwa 

1. There's a secret which is created and stored in the AWS secrets manage. The lambda has permission to get secrets, configured in the template.yml

**Comment by hackartisan** [comment]
Implementation is done but we want to create a diagram to document the architecture. Will close when that's finished.

**Comment by hackartisan** [comment]
Sequence diagram created at https://lucid.app/publicSegments/view/c63d2bcd-c5ba-4d92-aacc-56710638c065/image.pdf
